version: '3.9'
services:
  charli3-backend:
    image: charli3-backend:latest
    volumes:
      - "./config.yml:/app/config.yml"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node-operator-backend
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
