version: '3.9'
services:
  charli3-backend:
    image: ghcr.io/charli3-official/charli3-node-operator-backend:latest
    volumes:
      - "./config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
      - "./keys:/app/keys:ro"  # Place optional signing/verification key files here
    restart: always
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-node-operator-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node-operator-backend
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  charli3-migrations:
    image: ghcr.io/charli3-official/charli3-node-operator-backend:latest
    volumes:
      - "./config.yml:/app/config.yml"
    command: ["python3", "migrations.py"]
    depends_on:
      charli3-node-operator-db:
        condition: service_healthy
