Updater:
  update_inter: 60
  verbosity: INFO
  percent_resolution: 10000

database:
  url: "postgresql+asyncpg://postgres:password@localhost:5432/node-operator"

Alerts:
  cooldown: 1800 # 30 minutes (Optional)
  thresholds: # (Optional)
    c3_token_balance: 1000 # in ADA format
    ada_balance: 500 # in ADA
    timeout_variance: 105 # 5% variance
    minimum_data_sources: 3
  notifications: # at least one notification is required
    - type: slack
      config:
        webhook_url: "{tokenA}/{tokenB}/{tokenC}" # from https://hooks.slack.com/services/{tokenA}/{tokenB}/{tokenC}
    - type: discord
      config:
        webhook_url: "{WebhookID}/{WebhookToken}" # from Discord webhook https://discordapp.com/api/webhooks/{WebhookID}/{WebhookToken}
    - type: telegram
      config: # need to create a bot and get the token from BotFather
        bot_token: your_bot_token
        chat_id: your_chat_id

ChainQuery:
  network: TESTNET
  use_slot_time: false
  ogmios:
    ws_url: ws://35.222.137.225:1337
    kupo_url: http://35.222.137.225:1442

  external:
    ogmios:
      ws_url: ws:// #MAINNET
      kupo_url: http:// #MAINNET
    blockfrost:
      project_id: "mainnet....."

RewardCollection:
  destination_address: "addr_test1wqf99gagnjgfamek9v9vyrwulwh64xdnerq9xkvfhwyeu3qdufj2x" # Address to collect rewards
  trigger_amount: 1000 # 1000 C3 tokens

mnemonic_ada_charli3: "your mnemonic here"
