Updater:
  update_inter: 180
  verbosity: INFO
  percent_resolution: 10000

Node:
  signing_key: node3.skey
  verification_key: node3.vkey
  oracle_curr: 2e527c8e42d0f28fd3f4025f60c0a89bc5815c8e2efc3fb973e3fc20
  oracle_addr: addr_test1wz6jdu4f0eeamgzz2a8wt3eufux33nv6ju35z6r4de5rl0sncyqgh
  c3_token_hash: 436941ead56c61dbf9b92b5f566f7d5b9cac08f8c957f28f0bd60d4b
  c3_token_name: PAYMENTTOKEN
  c3_oracle_nft_name: "OracleFeed"
  c3_oracle_nft_hash: "ca9a3d8457735b989628ef1193a62f40799680e2bfcaf8936211420c"
  c3_oracle_rate_address: "addr_test1wqf99gagnjgfamek9v9vyrwulwh64xdnerq9xkvfhwyeu3qdufj2x"
  reward_collection_trigger: 100000000
  reward_destination_address: "addr_test1wqf99gagnjgfamek9v9vyrwulwh64xdnerq9xkvfhwyeu3qdufj2x"

ChainQuery:
  network: TESTNET
  blockfrost:
    base_url: https://cardano-preprod.blockfrost.io/api
    project_id: preprodVPAHdGNLvQtM3Ppkxtvd2oEVhHFxZ6MD
    max_api_calls: 50000
  ogmios:
    ws_url:  wss://ogmios-preprod-api-charli3-49bb04.us1.demeter.run
    kupo_url: kupo-preprod-api-charli3-49bb04.us1.demeter.run

Rate:
  base_currency:
    sundaeswap:
      type: sundaeswap
      symbol: Shen
      quote_currency: True
    minswap:
      type: minswap
      token_a_name: ADA
      token_a_decimal: 6
      token_b_name: MIN
      token_b_decimal: 6
      pool_id: 53225313968e796f2c1e0b57540a13c3b81e06e2ed2637ac1ea9b9f4e27e3dc4
      get_second_pool_price: False
      quote_currency: True
    vyfi:
      type: vyfi
      pool_tokens: ADA-ShenMicroUSD
      pool_address: addr1z8q336qgth58526mgr72svdlcqvs2jrkxem3thxnuqw4efk08470jem2z3k5yap4fddtxvykxxv2tmr83x06vklv5vys3jhn6c
      minting_a_token_policy:
      minting_b_token_policy: 8db269c3ec630e06ae29f74bc39edd1f87c819f1056206e879a1cd61
      get_second_pool_price: False
      quote_currency: True
    muesliswap:
      type: muesliswap
      symbol: SHEN/ADA
      currency_symbol: 8db269c3ec630e06ae29f74bc39edd1f87c819f1056206e879a1cd61
      token_name: 5368656e4d6963726f555344
      quote_currency: True
    bitrue:
      type: generic
      symbol: SHENUSDT
      api_url: https://openapi.bitrue.com
      path: /api/v1/ticker/price?symbol=shenusdt
      json_path: ["price"]
      key: {}
  quote_currency:
    binance:
      type: binance
      symbol: ADAUSDT
    kucoin:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.kucoin.com
      path: /api/v1/prices?currencies=ADA
      json_path: ["data","ADA"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    bitrue:
      type: generic
      symbol: ADAUSDT
      api_url: https://openapi.bitrue.com
      path: /api/v1/ticker/price?symbol=adausdt
      json_path: ["price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    charli3:
      type: charli3
      network_tokens: ADA-USD
      network_address: addr1wyd8cezjr0gcf8nfxuc9trd4hs7ec520jmkwkqzywx6l5jg0al0ya
      network_minting_policy: 3d0d75aad1eb32f0ce78fb1ebc101b6b51de5d8f13c12daa88017624
