include: example-dynamic-config.yml

Node:
  mnemonic: <%= @mnemonic_ada_charli3 %>
  oracle_curr: 2e527c8e42d0f28fd3f4025f60c0a89bc5815c8e2efc3fb973e3fc20
  oracle_address: addr_test1wz6jdu4f0eeamgzz2a8wt3eufux33nv6ju35z6r4de5rl0sncyqgh
  c3_token_hash: 436941ead56c61dbf9b92b5f566f7d5b9cac08f8c957f28f0bd60d4b
  c3_token_name: PAYMENTTOKEN
  c3_oracle_nft_name: "OracleFeed"
  c3_oracle_nft_hash: "ca9a3d8457735b989628ef1193a62f40799680e2bfcaf8936211420c"
  c3_oracle_rate_address: "addr_test1wqf99gagnjgfamek9v9vyrwulwh64xdnerq9xkvfhwyeu3qdufj2x"
  reward_collection_trigger: 100000000
  reward_destination_address: "addr_test1wqf99gagnjgfamek9v9vyrwulwh64xdnerq9xkvfhwyeu3qdufj2x"

Rate:
  general_base_symbol: COPI-ADA
  general_quote_symbol: ADA-USD
  # For micro-cap tokens like HOSKY, use higher precision: 1000000000000 = 1e12
  # precision_multiplier: 1000000000000
  precision_multiplier: 1000000  # Default 1e6 precision (suitable for most feeds)
  min_requirement: false # Optional default set to true. This will allow the the node to run even will less than 3 base data sources.
  base_currency:
    dexes:
      - adapter: charli3-dendrite
        asset_a: b6a7467ea1deb012808ef4e87b5ff371e85f7142d7b356a40d9b42a0436f726e75636f70696173205b76696120436861696e506f72742e696f5d
        asset_b: lovelace
        quote_required: true
        quote_calc_method: multiply # Optional: multiply by default | divide
        sources:
          - minswapv2
          - vyfi
          - spectrum
          - muesliswap
    api_sources:
      - adapter: generic-api
        asset_a: Cornucopias [via ChainPort.io]
        asset_b: USD
        quote_required: false
        sources:
          - name: gate
            api_url: "https://api.gateio.ws/api2/1/ticker/copi_usdt"
            json_path: ["last"]
            headers: {}

          - name: bitrue
            api_url: "https://openapi.bitrue.com/api/v1/ticker/price?symbol=copiusdt"
            json_path: ["price"]
            headers: {}

          - name: mexc
            api_url: "https://www.mexc.com/open/api/v2/market/ticker?symbol=COPI_USDT"
            json_path: ["data", 0, "last"]
            headers: {}

          - name: xt
            api_url: "https://sapi.xt.com/v4/public/ticker?symbol=COPI_usdt"
            json_path: ["result", 0, "c"]
            headers: {}

  quote_currency:
    api_sources:
      - adapter: generic-api
        asset_a: ADA
        asset_b: USDT
        sources:
          - name: xt
            api_url: "https://sapi.xt.com/v4/public/ticker?symbol=ada_usdt"
            json_path: ["result", 0, "c"]
            headers: {}

          - name: gate
            api_url: "https://api.gateio.ws/api2/1/ticker/ada_usdt"
            json_path: ["last"]
            headers: {}

          - name: crypto
            api_url: "https://api.crypto.com/v2/public/get-ticker?instrument_name=ADA_USDT"
            json_path: ["result", "data", 0, "a"]
            headers: {}

          - name: huobi
            api_url: "https://api.huobi.pro/market/trade?symbol=adausdt"
            json_path: ["tick", "data", 0, "price"]
            headers: {}

          - name: coinbase
            api_url: "https://api.exchange.coinbase.com/products/ADA-USD/ticker/"
            json_path: ["price"]
            headers: {}

          - name: kraken
            api_url: "https://api.kraken.com/0/public/Ticker?pair=ADAUSD"
            json_path: ["result", "ADAUSD", "o"]
            headers: {}

          - name: btse
            api_url: "https://api.btse.com/spot/api/v3.2/price?symbol=ADA-USD"
            json_path: [0, "lastPrice"]
            headers: {}

          - name: bitfinex
            api_url: "https://api.bitfinex.com/v2/ticker/tADAUSD"
            json_path: [6]
            headers: {}

          - name: bitget
            api_url: "https://api.bitget.com/api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL"
            json_path: ["data", "close"]
            headers: {}

          - name: kucoin
            api_url: "https://api.kucoin.com/api/v1/market/orderbook/level1?symbol=ADA-USDC"
            json_path: ["data", "price"]
            headers: {}

          - name: okx
            api_url: "https://www.okx.com/api/v5/market/ticker?instId=ADA-USDC"
            json_path: ["data", 0, "last"]
            headers: {}
    
    cexes:
      - adapter: ccxt  # Centralized exchange integration adapter
        asset_a: "ADA"  # First asset symbol in trading pair (e.g., ADA)
        asset_b: "USDT"  # Second asset symbol in trading pair (e.g., USDT)
        quote_required: false
        quote_calc_method: multiply
        sources:
          - alpaca
          - ascendex
          - bequant
          - bigone
          - binance
          - binancecoinm
          - binanceus
          - binanceusdm
          - bingx
          - bit2c
          - bitbank
          - bitbns
          - bitfinex
          - bitflyer
          - bitget
          - bithumb
          - bitmart
          - bitmex
          - bitopro
          - bitrue
          - bitso
          - bitstamp
          - bitteam
          - bittrade
          - bitvavo
          - blockchaincom
          - blofin
          - btcalpha
          - btcbox
          - btcmarkets
          - btcturk
          - bybit
          - cex
          - coinbase
          - coinbaseexchange
          - coinbaseinternational
          - coincatch
          - coincheck
          - coinex
          - coinmate
          - coinmetro
          - coinone
          - coinsph
          - coinspot
          - cryptocom
          - cryptomus
          - delta
          - deribit
          - digifinex
          - exmo
          - fmfwio
          - foxbit
          - gate
          - gemini
          - hashkey
          - hitbtc
          - hollaex
          - htx
          - independentreserve
          - indodax
          - kraken
          - krakenfutures
          - kucoin
          - kucoinfutures
          - latoken
          - lbank
          - luno
          - mercado
          - mexc
          - myokx
          - ndax
          - novadax
          - oceanex
          - okcoin
          - okx
          - okxus
          - onetrading
          - oxfun
          - p2b
          - paymium
          - phemex
          - poloniex
          - probit
          - timex
          - tokocrypto
          - tradeogre
          - upbit
          - whitebit
          - woo
          - xt
          - yobit
          - zaif
          - zonda
