Updater:
  update_inter: 60
  verbosity: INFO
  percent_resolution: 10000

database:
  url: "postgresql+asyncpg://postgres:password@localhost:5432/node-operator"

SlackAlerts:
  token:
  channel:
  minimum_data_sources:

ChainQuery:
  network: TESTNET
  ogmios:
    ws_url: ws://35.222.137.225:1337
    kupo_url: http://35.222.137.225:1442
    pyogmios: # False

mnemonic_ada_charli3: "your mnemonic here"
